services:
  chromadb-api:
    container_name: chromadb-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - DISABLE_SSL_VERIFICATION=true
      - CHROMA_HOST=http://chromadb:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_KEY=${API_KEY}
    networks:
      - dokploy-network
    depends_on:
      - chromadb
    restart: unless-stopped
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma:/data
    networks:
      - dokploy-network
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data
      - OPENAI_API_KEY=${OPEN_API_KEY}

networks:
  dokploy-network:
    external: true
    
volumes:
  chroma:
    name: chroma
