services:
  chromadb-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - DISABLE_SSL_VERIFICATION=true
      - CHROMA_HOST=http://chromadb:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_KEY=${API_KEY}
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true